version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11.9

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run test

workflows:
  version: 2

  test:
    jobs:
      - build
